# Generated by Django 4.0.5 on 2022-07-10 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itpBlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='uploading_date',
            new_name='publication_date',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='summary_text',
            new_name='summary',
        ),
    ]
