# Generated by Django 4.0.5 on 2022-08-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpBlog', '0002_alter_article_full_text_alter_article_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(help_text='Readable link to the article, example: first_article', max_length=255, unique=True),
        ),
    ]
