# Generated by Django 4.0.5 on 2022-08-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itpBlog', '0003_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.CharField(max_length=511),
        ),
    ]
