# Generated by Django 4.0.5 on 2022-08-15 00:02

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('itpBlog', '0004_alter_article_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_text', tinymce.models.HTMLField()),
            ],
        ),
    ]
